Public without sharing class VCCEmailToCaseUtil{
    public Static void meth1(){
        String loggedInUserEmailAdress = UserInfo.getUserEmail();
        String fromEmailAdress;
        /*EmailToCaseMapping__c email2Case = EmailToCaseMapping__c.getValues('VCCEmailToCase');
        fromEmailAdress = email2Case.EmailToCaseValue__c;
        system.debug('@@@@@@@@@@' +fromEmailAdress);*/
        
    }
}